---
- name: Install Monitoring Server (prometheus & Grafana)
  hosts: monitor
  become: true
  roles:
    # -------------------------------------------
    # 1. Role AlertManager (Si Pengirim Pesan Telegram)
    # -------------------------------------------
    - role: prometheus.prometheus.alertmanager
      vars:
        alertmanager_version: "0.25.0"

        # Konfigurasi Penerima (Telegram)
        alertmanager_receivers:
          - name: 'telegram-bot'
            telegram_configs:
              - bot_token: '7986889247:AAFQeKWyNTjdPk5jquYPZsqBLG9JV88aW3Q' # Gunakan tanda kutip agar aman
                chat_id: 853460879
                parse_mode: 'HTML'
                message: "🚨 <b>{{ '{{' }} .Status | toUpper {{ '}}' }}</b>: {{ '{{' }} .CommonAnnotations.summary {{ '}}' }}\n\nDetail: {{ '{{' }} .CommonAnnotations.description {{ '}}' }}"

        # Konfigurasi Rute (Kirim semua alert ke telegram-bot)
        alertmanager_route:
          group_by: ['alertname']
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 1h
          receiver: 'telegram-bot'

    # -------------------------------------------
    # 2. Role Prometheus (Si Pendeteksi Masalah)
    # -------------------------------------------
    - role: prometheus.prometheus.prometheus
      vars:
        prometheus_version: "2.45.0"
        
        # Agar Prometheus tahu kemana harus kirim alert (ke Alertmanager localhost:9093)
        prometheus_alertmanager_config:
          - static_configs:
              - targets: ['localhost:9093']

        prometheus_scrape_configs:
          - job_name: 'node_exporter'
            scrape_interval: 15s
            static_configs:
              - targets: "{{ groups['all'] | map('regex_replace', '$', ':9100') | list }}"

        # Definisi Aturan Alert (Kapan harus teriak?)
        prometheus_alert_rules:
          # ALERT 1: Jika Server Mati (Instance Down)
          - alert: InstanceDown
            expr: up == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              # Escape kurung kurawal agar Ansible tidak bingung
              summary: "Host {{ '{{' }} $labels.instance {{ '}}' }} MATI!"
              description: "Server tidak bisa dihubungi lebih dari 1 menit."

          # ALERT 2: Jika CPU > 90%
          - alert: HighCPUUsage
            expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 90
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "CPU Tinggi di {{ '{{' }} $labels.instance {{ '}}' }}"
              description: "CPU Usage tembus di atas 90%."

    # -------------------------------------------
    # 3. Role Grafana (Si Penampil Data)
    # -------------------------------------------
    - role: hax0rbana_adam.grafana
      vars:
        grafana_security:
          admin_user: admin
          admin_password: admin123
        grafana_dashboards:
          - dashboard_id: 1860
            revision_id: 37
            datasource: Prometheus
        grafana_datasources:
          - name: Prometheus       # Nama ini harus sama dengan referensi di dashboard
            type: prometheus
            access: proxy
            url: 'http://localhost:9090'
            basicAuth: false
        # -----------------------------------

        grafana_dashboards:
          - dashboard_id: 1860
            revision_id: 37
            datasource: Prometheus
