- name: deploy web dengan shared storage
  hosts: managers
  become: true
  tasks:
    - name: hapus Service lama
      community.docker.docker_swarm_service:
        name: my-cluster-web
        state: absent

    - name: Deploy Nginx dengan NFS volume
      community.docker.docker_swarm_service:
        name: my-cluster-web
        image: nginx:alpine
        replicas: 5
        publish:
          - published_port: 8000
            target_port: 80
        mounts:
          - source: /mnt/shared-web
            target: /usr/share/nginx/html
            type: bind
        state: present
