- name: Deploy Service ke Docker Swarm
  hosts: managers
  become: true
  tasks:
    # Aplikasi Visualizer (Hanya jalan di host Manager)
    - name: Deploy Swarm Visualizer
      community.docker.docker_swarm_service:
        name: viz
        image: dockersamples/visualizer
        publish:
          - published_port: 8888
            target_port: 8080
        placement:
          constraints:
          - node.role == manager
        mounts:
          - source: /var/run/docker.sock
            target: /var/run/docker.sock
            type: bind
        state: present

    # Aplikasi Web Cluster (Disebar ke 5 Replika)
    - name: Deploy Web Cluster (WhoAmI)
      community.docker.docker_swarm_service:
        name: my-cluster-web
        image: jwilder/whoami
        replicas: 5
        publish:
          - published_port: 8000
            target_port: 8000
        state: present
