---
- name: Deploy Nginx Proxy Manager
  hosts: all
  become: true
  tasks:
    - name: Buat direktori data untuk NPM
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /opt/npm
        - /opt/npm/data
        - /opt/npm/letsencrypt

    - name: Deploy Container Nginx Proxy Manager
      community.docker.docker_container:
        name: nginx-proxy-manager
        image: 'jc21/nginx-proxy-manager:latest'
        state: started
        restart_policy: always
        ports:
          - "80:80"       
          - "443:443"     
          - "81:81"       # Pintu Admin Dashboard
        volumes:
          - "/opt/npm/data:/data"
          - "/opt/npm/letsencrypt:/etc/letsencrypt"
